// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';
export const LOGGING = '@customization/LOGGING';
export const LOGOUT = '@customization/LOGOUT';
export const ADD_TO_CART = '@customization/ADD_TO_CART';
export const RESET_CART = '@customization/RESET_CART';
export const UPDATE_CART = '@customization/UPDATE_CART';
export const REMOVE_FROM_CART = '@customization/REMOVE_FROM_CART';